import type { Finding, Severity } from "../scanner/types.ts";
import { SEVERITIES } from "../scanner/types.ts";
import type { ProjectDetail, RepositoryScan } from "./types.ts";

export interface ReportItem { id: string; title: string; severity: Severity; category: string; filePath: string; status: "VERIFIED RESOLVED" | "REMAINING" | "NEW" }
export function compareRepositoryScans(before: RepositoryScan, after: RepositoryScan) {
  if (before.projectId !== after.projectId || before.scanId === after.scanId || Date.parse(after.scannedAt) < Date.parse(before.scannedAt)) {
    throw new Error("Comparison requires separate ordered scans of the same project.");
  }
  const old = new Set(before.findings.map((f) => f.id));
  const current = new Set(after.findings.map((f) => f.id));
  return { previousScore: before.score, newScore: after.score, improvement: after.score - before.score,
    disappeared: before.findings.filter((f) => !current.has(f.id)),
    remaining: after.findings.filter((f) => old.has(f.id)),
    newFindings: after.findings.filter((f) => !old.has(f.id)) };
}
function reportItem(finding: Finding, status: ReportItem["status"]): ReportItem {
  return { id: finding.id, title: finding.title, severity: finding.severity, category: finding.category, filePath: finding.filePath, status };
}
export function createSecurityReport(detail: ProjectDetail, date = new Date().toISOString()) {
  const baseline = detail.scans[0];
  if (!baseline) throw new Error("Run a baseline scan to generate a report.");
  const final = detail.scans.at(-1)!;
  const comparison = baseline === final ? null : compareRepositoryScans(baseline, final);
  return {
    title: "HackForge Security Improvement Report", reportDate: date,
    project: { id: detail.project.id, name: detail.project.name, repository: detail.project.repositoryUrl,
      owner: detail.project.repositoryOwner },
    evidence: { baselineCommitSha: baseline.commitSha, finalCommitSha: final.commitSha,
      baselineScanId: baseline.scanId, finalScanId: final.scanId,
      baselineSandboxMode: baseline.sandboxMode, finalSandboxMode: final.sandboxMode },
    summary: { baselineScore: baseline.score, finalScore: final.score,
      verifiedImprovement: comparison?.improvement ?? 0,
      baselineFindings: baseline.findings.length, finalFindings: final.findings.length },
    severity: { baseline: baseline.counts, final: final.counts },
    verifiedResolutions: (comparison?.disappeared ?? []).map((f) => reportItem(f, "VERIFIED RESOLVED")),
    remainingFindings: (comparison?.remaining ?? final.findings).map((f) => reportItem(f, "REMAINING")),
    newFindings: (comparison?.newFindings ?? []).map((f) => reportItem(f, "NEW")),
    coverage: { baseline: baseline.coverage, final: final.coverage, scannerVersion: final.scannerVersion },
    methodology: ((baseline.sandboxMode === "LOCAL_STATIC" || final.sandboxMode === "LOCAL_STATIC")
      ? "Repository analysis was performed in a temporary local workspace using static analysis only. Repository application code and package scripts were not executed. " : "") + "Findings are generated by HackForge's deterministic SAI Security Scanner. AI assistance is used only to explain verified findings and does not determine findings, severity, scoring, or resolution.",
    limitations: "This report reflects only the checks supported by the HackForge scanner and is not a guarantee that the repository is free of vulnerabilities.",
  };
}
export function renderSecurityReport(detail: ProjectDetail): string {
  const report = createSecurityReport(detail);
  const escape = (value: string | number) => String(value).replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]!);
  const list = (items: ReportItem[]) => items.length ? `<ul>${items.map((item) => `<li><strong>${escape(item.title)}</strong> · ${escape(item.severity)} · ${escape(item.category)} · <code>${escape(item.filePath)}</code> · ${escape(item.status)}</li>`).join("")}</ul>` : "<p>None.</p>";
  const severity = (counts: Record<Severity, number>) => `<dl>${SEVERITIES.map((name) => `<dt>${name}</dt><dd>${escape(counts[name])}</dd>`).join("")}</dl>`;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>HackForge Security Improvement Report</title><style>
    body{font:16px/1.5 system-ui,sans-serif;color:#172d40;max-width:850px;margin:auto;padding:2rem}h1,h2{color:#122b40}section{border-top:1px solid #ccd8dc;padding:1rem 0}dl{display:grid;grid-template-columns:170px 1fr;gap:.4rem}dd{margin:0}code{overflow-wrap:anywhere}.scores{display:flex;gap:1rem;flex-wrap:wrap}.scores div{padding:1rem;background:#eaf6f0;border-radius:12px}.print{position:fixed;top:1rem;right:1rem}li{margin:.5rem 0}@media print{body{max-width:none}.print{display:none}section{break-inside:avoid}}
  </style></head><body><button class="print" type="button" onclick="window.print()">Print / Save PDF</button>
    <h1>${escape(report.title)}</h1><p>Report date: ${escape(report.reportDate)}</p>
    <section><h2>1. Project information</h2><dl><dt>Project</dt><dd>${escape(report.project.name)}</dd><dt>Repository</dt><dd>${escape(report.project.repository)}</dd><dt>Owner</dt><dd>${escape(report.project.owner)}</dd></dl></section>
    <section><h2>2. Repository evidence</h2><dl><dt>Baseline commit</dt><dd><code>${escape(report.evidence.baselineCommitSha)}</code></dd><dt>Final commit</dt><dd><code>${escape(report.evidence.finalCommitSha)}</code></dd></dl></section>
    <section><h2>3. Executive summary</h2><div class="scores"><div>Baseline <strong>${report.summary.baselineScore} / 100</strong><br>${report.summary.baselineFindings} findings</div><div>Final <strong>${report.summary.finalScore} / 100</strong><br>${report.summary.finalFindings} findings</div><div>Change <strong>${report.summary.verifiedImprovement >= 0 ? "+" : ""}${report.summary.verifiedImprovement}</strong></div></div></section>
    <section><h2>4. Severity summary</h2><h3>Baseline</h3>${severity(report.severity.baseline)}<h3>Final</h3>${severity(report.severity.final)}</section>
    <section><h2>5. Verified resolutions</h2>${list(report.verifiedResolutions)}</section>
    <section><h2>6. Remaining findings</h2>${list(report.remainingFindings)}</section>
    <section><h2>7. New findings</h2>${list(report.newFindings)}</section>
    <section><h2>8. Security improvement</h2><p>${report.summary.baselineScore} / 100 → ${report.summary.finalScore} / 100; ${report.summary.verifiedImprovement >= 0 ? "+" : ""}${report.summary.verifiedImprovement} point change verified by deterministic rescanning.</p></section>
    <section><h2>9. Methodology</h2><p>${escape(report.methodology)}</p></section>
    <section><h2>10. Limitations</h2><p>${escape(report.limitations)}</p><p>Only secret and Git hygiene checks are supported. Filenames are masked for privacy. An unchanged commit or an initial baseline does not demonstrate a fix. Results reflect the current snapshot, not historical exposure. Binary files and generated directories are skipped, as listed in JSON coverage.</p></section>
  </body></html>`;
}
